-- +goose Up
ALTER TABLE users ADD COLUMN "bio"   TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN "track" TEXT NOT NULL DEFAULT '';

-- +goose Down
ALTER TABLE users DROP COLUMN "bio";
ALTER TABLE users DROP COLUMN "track";
